export const birds = 
[{id : 0, name : 'Indigo Bunting', imgUrl :'https://www.birdphotography.com/species/photos/inbu-6.jpg', count : 0},
{id : 1, name: 'American Bittern',imgUrl :'https://www.birdphotography.com/species/photos/ambi-10.jpg', count : 0},
{id : 2,name: 'Cassin’s Auklet', imgUrl:'https://www.birdphotography.com/species/photos/caau-8.jpg',  count : 0},
{id : 3,name: 'Crested Auklet', imgUrl:'https://www.birdphotography.com/species/photos/crau-1.jpg',  count : 0},
{id : 4,name: 'Least Auklet', imgUrl:'https://www.birdphotography.com/species/photos/leau-2.jpg',  count : 0},
{id : 5,name: 'Parakeet Auklet', imgUrl:'https://www.birdphotography.com/species/photos/paau-1.jpg',  count : 0},
{id : 6,name: 'Brewer’s Blackbird', imgUrl:'https://www.birdphotography.com/species/photos/brbl-6.jpg',  count : 0},
{id : 7,name: 'Red-winged Blackbird', imgUrl:'https://www.birdphotography.com/species/photos/rwbl-10.jpg',  count : 0},
{id : 8,name: 'Rusty Blackbird', imgUrl:'https://www.birdphotography.com/species/photos/rubl-2.jpg',  count : 0},
{id : 9,name: 'Tricolored Blackbird', imgUrl:'https://www.birdphotography.com/species/photos/trbl-13.jpg',  count : 0},
{id : 10,name: 'Lark Bunting', imgUrl:'https://www.birdphotography.com/species/photos/larb-1.jpg',  count : 0},
{id : 11,name: 'Mexican Chickadee', imgUrl:'https://www.birdphotography.com/species/photos/mech-1.jpg',  count : 0},
{id : 12,name: 'Mountain Chickadee', imgUrl:'https://www.birdphotography.com/species/photos/moch-9.jpg',  count : 0},
{id : 13,name: 'Bronzed Cowbird', imgUrl:'https://www.birdphotography.com/species/photos/broc-3.jpg',  count : 0},
{id : 14,name: 'Sandhill Crane', imgUrl:'https://www.birdphotography.com/species/photos/sacr-19.jpg',  count : 0},
{id : 15,name: 'Brandt’s Cormorant', imgUrl:'https://www.birdphotography.com/species/photos/brac-11.jpg',  count : 0},
{id : 16,name: 'Brown Creeper', imgUrl:'https://www.birdphotography.com/species/photos/brcr-7.jpg',  count : 0},
{id : 17,name: 'Double-crested Cormorant', imgUrl:'https://www.birdphotography.com/species/photos/dcco-7.jpg',  count : 0},
{id : 18,name: 'American Crow', imgUrl:'https://www.birdphotography.com/species/photos/amcr-8.jpg',  count : 0},
{id : 19,name: 'Yellow-billed Cuckoo', imgUrl:'https://www.birdphotography.com/species/photos/ybcu-1.jpg',  count : 0},
{id : 20,name: 'Fish Crow', imgUrl:'https://www.birdphotography.com/species/photos/ficr-2.jpg',  count : 0}]